In [2]:
import pandas as pd

In [3]:
#importing violation dataset
Violations = pd.read_csv("DOHMH_Childcare_Center_Inspections_(Historical)_20260511.csv")
Violations

,Center Name,Legal Name,Building,Street,Borough,ZipCode,Phone,Permit Number,Permit Expiration,Status,...,Public Health Hazard Violation Rate,Average Public Health Hazard Violation Rate,Critical Violation Rate,Average Critical Violation Rate,Inspection Date,Regulation Summary,Violation Category,Health Code Sub Section,Violation Status,Inspection Summary Result
0,"JACKSON CHILDREN'S SERVICES, INC.","JACKSON CHILDREN'S SERVICES, INC.",88-23,31 AVENUE,QUEENS,11369.0,718-205-1919,105769.0,8/10/24,Permitted,...,0.0000,6.1285,50.0000,18.9541,12/7/22,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...
1,"JACKSON CHILDREN'S SERVICES, INC.","JACKSON CHILDREN'S SERVICES, INC.",88-23,31 AVENUE,QUEENS,11369.0,718-205-1919,105769.0,8/10/24,Permitted,...,0.0000,6.1285,50.0000,18.9541,12/7/22,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...
2,ATERET TORAH CENTER,BET YAAKOV ATERET TORAH,2166,CONEY ISLAND AVENUE,BROOKLYN,11223.0,718-375-7100,NaN,1/23/15,Active,...,0.0000,23.3017,50.0000,35.2291,10/20/22,School-based child care staff observed caring ...,GENERAL,43.11(b),OPEN,Initial Annual Inspection - Reinspection Required
3,PACKER SUMMER 2022,PACKER COLLEGIATE INSTITUTE,170,Joralemon Street,BROOKLYN,11201.0,718-250-0259,33693.0,9/15/22,Expired-In Renewal,...,0.0000,14.2558,0.0000,21.8553,6/22/22,There were no new violations observed at the t...,NaN,NaN,NaN,Initial Annual Inspection - Passed inspection ...
4,THE LEARNING EXPERIENCE,"RIVERDALE CHILDCARE EXPERIENCE, LLC",3210,Riverdale Avenue,BRONX,10463.0,718-708-5884,97738.0,9/28/23,Permitted,...,NaN,NaN,NaN,NaN,11/5/21,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27823,BRIGHT BEGINNINGS EARLY LEARNING CENTER,SIDI INC.,2160,EAST TREMONT AVENUE,BRONX,10462.0,718-822-2586,98297.0,10/8/23,Permitted,...,16.6667,6.1285,66.6667,18.9541,3/28/23,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN
27824,"Teeny Tiny Toes, LLC","Teeny Tiny Toes, LLC",19-79,38 Street,QUEENS,11105.0,347-801-3103,105314.0,4/13/25,Permitted,...,0.0000,6.1285,33.3333,18.9541,9/26/22,There were no new violations observed at the t...,NaN,NaN,NaN,NaN
27825,"BETH JACOB DAY CARE CENTER, INC.","BETH JACOB DAY CARE CENTER,INC.",1363,46TH STREET,BROOKLYN,11219.0,718-435-5755,4735.0,2/2/24,Permitted,...,0.0000,6.1285,0.0000,18.9541,2/8/23,There were no new violations observed at the t...,NaN,NaN,NaN,Initial Annual Inspection - Passed inspection ...
27826,"THE EAST CHELSEA CHILDRENS WORKSHOP, INC.","THE EAST CHELSEA CHILDRENS WORKSHOP, INC.",17,EAST 16TH STREET,MANHATTAN,10003.0,212-691-8964,4869.0,7/15/23,Permitted,...,0.0000,6.1285,50.0000,18.9541,4/21/21,Consent to provide emergency medical care for ...,GENERAL,47..29(b)(1)(A),CORRECTED,Initial Annual Inspection - Passed inspection;...
27827,CHILDREN OF AMERICA QUEENS,"CHILDREN OF AMERICA QUEENS, LLC",33-06,88 STREET,QUEENS,11372.0,347-730-5438,103774.0,8/23/24,Permitted,...,NaN,NaN,NaN,NaN,8/22/22,Constant and competent supervision provided by...,PUBLIC HEALTH HAZARD,47.23(a),CORRECTED,Compliance Inspection of Open Violations - Rei...

In [4]:
#also, only allow childcare: ages 0-5
allowed_ages = ["0 YEARS - 2 YEARS", "2 YEARS - 5 YEARS", "3 YEARS - 5 YEARS"]
Violations = Violations[
    Violations["Age Range"].isin(allowed_ages)]

#validate that
Violations["Age Range"].value_counts(dropna=False)

Age Range
2 YEARS - 5 YEARS    17753
0 YEARS - 2 YEARS     3619
3 YEARS - 5 YEARS     3499
Name: count, dtype: int64

In [5]:
#Make everything title case
Violations["Center Name"] = (Violations["Center Name"].astype(str).str.strip().str.title())
Violations["Legal Name"] = (Violations["Legal Name"].astype(str).str.strip().str.title())
Violations["Street"] = (Violations["Street"].astype(str).str.strip().str.title())
Violations["Building"] = Violations["Building"].astype(str).str.strip()
Violations["Street"] = Violations["Street"].astype(str).str.strip()

Violations

,Center Name,Legal Name,Building,Street,Borough,ZipCode,Phone,Permit Number,Permit Expiration,Status,...,Public Health Hazard Violation Rate,Average Public Health Hazard Violation Rate,Critical Violation Rate,Average Critical Violation Rate,Inspection Date,Regulation Summary,Violation Category,Health Code Sub Section,Violation Status,Inspection Summary Result
0,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369.0,718-205-1919,105769.0,8/10/24,Permitted,...,0.0000,6.1285,50.0000,18.9541,12/7/22,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...
1,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369.0,718-205-1919,105769.0,8/10/24,Permitted,...,0.0000,6.1285,50.0000,18.9541,12/7/22,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...
2,Ateret Torah Center,Bet Yaakov Ateret Torah,2166,Coney Island Avenue,BROOKLYN,11223.0,718-375-7100,NaN,1/23/15,Active,...,0.0000,23.3017,50.0000,35.2291,10/20/22,School-based child care staff observed caring ...,GENERAL,43.11(b),OPEN,Initial Annual Inspection - Reinspection Required
4,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463.0,718-708-5884,97738.0,9/28/23,Permitted,...,NaN,NaN,NaN,NaN,11/5/21,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN
5,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463.0,718-708-5884,97738.0,9/28/23,Permitted,...,NaN,NaN,NaN,NaN,11/5/21,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27822,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462.0,718-822-2586,98297.0,10/8/23,Permitted,...,16.6667,6.1285,66.6667,18.9541,3/28/23,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN
27823,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462.0,718-822-2586,98297.0,10/8/23,Permitted,...,16.6667,6.1285,66.6667,18.9541,3/28/23,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN
27824,"Teeny Tiny Toes, Llc","Teeny Tiny Toes, Llc",19-79,38 Street,QUEENS,11105.0,347-801-3103,105314.0,4/13/25,Permitted,...,0.0000,6.1285,33.3333,18.9541,9/26/22,There were no new violations observed at the t...,NaN,NaN,NaN,NaN
27826,"The East Chelsea Childrens Workshop, Inc.","The East Chelsea Childrens Workshop, Inc.",17,East 16Th Street,MANHATTAN,10003.0,212-691-8964,4869.0,7/15/23,Permitted,...,0.0000,6.1285,50.0000,18.9541,4/21/21,Consent to provide emergency medical care for ...,GENERAL,47..29(b)(1)(A),CORRECTED,Initial Annual Inspection - Passed inspection;...
27827,Children Of America Queens,"Children Of America Queens, Llc",33-06,88 Street,QUEENS,11372.0,347-730-5438,103774.0,8/23/24,Permitted,...,NaN,NaN,NaN,NaN,8/22/22,Constant and competent supervision provided by...,PUBLIC HEALTH HAZARD,47.23(a),CORRECTED,Compliance Inspection of Open Violations - Rei...

In [6]:
# Convert Inspection Date to datetime
Violations["Inspection Date"] = pd.to_datetime(
    Violations["Inspection Date"],
    format="%m/%d/%y",
    errors="coerce")

# Convert ZipCode to float
Violations["ZipCode"] = Violations["ZipCode"].astype("Int64")
Violations

,Center Name,Legal Name,Building,Street,Borough,ZipCode,Phone,Permit Number,Permit Expiration,Status,...,Public Health Hazard Violation Rate,Average Public Health Hazard Violation Rate,Critical Violation Rate,Average Critical Violation Rate,Inspection Date,Regulation Summary,Violation Category,Health Code Sub Section,Violation Status,Inspection Summary Result
0,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369,718-205-1919,105769.0,8/10/24,Permitted,...,0.0000,6.1285,50.0000,18.9541,2022-12-07,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...
1,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369,718-205-1919,105769.0,8/10/24,Permitted,...,0.0000,6.1285,50.0000,18.9541,2022-12-07,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...
2,Ateret Torah Center,Bet Yaakov Ateret Torah,2166,Coney Island Avenue,BROOKLYN,11223,718-375-7100,NaN,1/23/15,Active,...,0.0000,23.3017,50.0000,35.2291,2022-10-20,School-based child care staff observed caring ...,GENERAL,43.11(b),OPEN,Initial Annual Inspection - Reinspection Required
4,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463,718-708-5884,97738.0,9/28/23,Permitted,...,NaN,NaN,NaN,NaN,2021-11-05,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN
5,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463,718-708-5884,97738.0,9/28/23,Permitted,...,NaN,NaN,NaN,NaN,2021-11-05,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27822,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462,718-822-2586,98297.0,10/8/23,Permitted,...,16.6667,6.1285,66.6667,18.9541,2023-03-28,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN
27823,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462,718-822-2586,98297.0,10/8/23,Permitted,...,16.6667,6.1285,66.6667,18.9541,2023-03-28,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN
27824,"Teeny Tiny Toes, Llc","Teeny Tiny Toes, Llc",19-79,38 Street,QUEENS,11105,347-801-3103,105314.0,4/13/25,Permitted,...,0.0000,6.1285,33.3333,18.9541,2022-09-26,There were no new violations observed at the t...,NaN,NaN,NaN,NaN
27826,"The East Chelsea Childrens Workshop, Inc.","The East Chelsea Childrens Workshop, Inc.",17,East 16Th Street,MANHATTAN,10003,212-691-8964,4869.0,7/15/23,Permitted,...,0.0000,6.1285,50.0000,18.9541,2021-04-21,Consent to provide emergency medical care for ...,GENERAL,47..29(b)(1)(A),CORRECTED,Initial Annual Inspection - Passed inspection;...
27827,Children Of America Queens,"Children Of America Queens, Llc",33-06,88 Street,QUEENS,11372,347-730-5438,103774.0,8/23/24,Permitted,...,NaN,NaN,NaN,NaN,2022-08-22,Constant and competent supervision provided by...,PUBLIC HEALTH HAZARD,47.23(a),CORRECTED,Compliance Inspection of Open Violations - Rei...

In [7]:
# Create unique center-location ID

# Clean fields
Violations["Building_clean"] = Violations["Building"].astype(str).str.strip().str.upper()
Violations["Street_clean"] = (
    Violations["Street"].astype(str).str.upper().str.strip().str.replace(r"\s+", " ", regex=True))

Violations["Phone_clean"] = (Violations["Phone"].astype(str).str.replace(r"\D", "", regex=True).str.strip())

Violations["ZipCode_clean"] = Violations["ZipCode"].astype("Int64").astype(str)

#Create one physical center/site ID

Violations["Center_Site_ID"] = (Violations["Building_clean"] + " "
    + Violations["Street_clean"] + " | "
    + Violations["ZipCode_clean"] + " | "
    + Violations["Phone_clean"])

Violations

,Center Name,Legal Name,Building,Street,Borough,ZipCode,Phone,Permit Number,Permit Expiration,Status,...,Regulation Summary,Violation Category,Health Code Sub Section,Violation Status,Inspection Summary Result,Building_clean,Street_clean,Phone_clean,ZipCode_clean,Center_Site_ID
0,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369,718-205-1919,105769.0,8/10/24,Permitted,...,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...,88-23,31 AVENUE,7182051919,11369,88-23 31 AVENUE | 11369 | 7182051919
1,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369,718-205-1919,105769.0,8/10/24,Permitted,...,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...,88-23,31 AVENUE,7182051919,11369,88-23 31 AVENUE | 11369 | 7182051919
2,Ateret Torah Center,Bet Yaakov Ateret Torah,2166,Coney Island Avenue,BROOKLYN,11223,718-375-7100,NaN,1/23/15,Active,...,School-based child care staff observed caring ...,GENERAL,43.11(b),OPEN,Initial Annual Inspection - Reinspection Required,2166,CONEY ISLAND AVENUE,7183757100,11223,2166 CONEY ISLAND AVENUE | 11223 | 7183757100
4,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463,718-708-5884,97738.0,9/28/23,Permitted,...,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN,3210,RIVERDALE AVENUE,7187085884,10463,3210 RIVERDALE AVENUE | 10463 | 7187085884
5,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463,718-708-5884,97738.0,9/28/23,Permitted,...,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN,3210,RIVERDALE AVENUE,7187085884,10463,3210 RIVERDALE AVENUE | 10463 | 7187085884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27822,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462,718-822-2586,98297.0,10/8/23,Permitted,...,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN,2160,EAST TREMONT AVENUE,7188222586,10462,2160 EAST TREMONT AVENUE | 10462 | 7188222586
27823,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462,718-822-2586,98297.0,10/8/23,Permitted,...,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN,2160,EAST TREMONT AVENUE,7188222586,10462,2160 EAST TREMONT AVENUE | 10462 | 7188222586
27824,"Teeny Tiny Toes, Llc","Teeny Tiny Toes, Llc",19-79,38 Street,QUEENS,11105,347-801-3103,105314.0,4/13/25,Permitted,...,There were no new violations observed at the t...,NaN,NaN,NaN,NaN,19-79,38 STREET,3478013103,11105,19-79 38 STREET | 11105 | 3478013103
27826,"The East Chelsea Childrens Workshop, Inc.","The East Chelsea Childrens Workshop, Inc.",17,East 16Th Street,MANHATTAN,10003,212-691-8964,4869.0,7/15/23,Permitted,...,Consent to provide emergency medical care for ...,GENERAL,47..29(b)(1)(A),CORRECTED,Initial Annual Inspection - Passed inspection;...,17,EAST 16TH STREET,2126918964,10003,17 EAST 16TH STREET | 10003 | 2126918964
27827,Children Of America Queens,"Children Of America Queens, Llc",33-06,88 Street,QUEENS,11372,347-730-5438,103774.0,8/23/24,Permitted,...,Constant and competent supervision provided by...,PUBLIC HEALTH HAZARD,47.23(a),CORRECTED,Compliance Inspection of Open Violations - Rei...,33-06,88 STREET,3477305438,11372,33-06 88 STREET | 11372 | 3477305438

In [8]:
#don't include instances of no new violations
Violations = Violations[~Violations["Regulation Summary"].str.contains(
"There were no new violations observed at the time of this inspection/visit",
        na=False)]
Violations

,Center Name,Legal Name,Building,Street,Borough,ZipCode,Phone,Permit Number,Permit Expiration,Status,...,Regulation Summary,Violation Category,Health Code Sub Section,Violation Status,Inspection Summary Result,Building_clean,Street_clean,Phone_clean,ZipCode_clean,Center_Site_ID
0,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369,718-205-1919,105769.0,8/10/24,Permitted,...,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...,88-23,31 AVENUE,7182051919,11369,88-23 31 AVENUE | 11369 | 7182051919
1,"Jackson Children'S Services, Inc.","Jackson Children'S Services, Inc.",88-23,31 Avenue,QUEENS,11369,718-205-1919,105769.0,8/10/24,Permitted,...,At time of inspection floors/walls ceilings we...,GENERAL,47.41(j),OPEN,Initial Annual Inspection - Reinspection Not R...,88-23,31 AVENUE,7182051919,11369,88-23 31 AVENUE | 11369 | 7182051919
2,Ateret Torah Center,Bet Yaakov Ateret Torah,2166,Coney Island Avenue,BROOKLYN,11223,718-375-7100,NaN,1/23/15,Active,...,School-based child care staff observed caring ...,GENERAL,43.11(b),OPEN,Initial Annual Inspection - Reinspection Required,2166,CONEY ISLAND AVENUE,7183757100,11223,2166 CONEY ISLAND AVENUE | 11223 | 7183757100
4,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463,718-708-5884,97738.0,9/28/23,Permitted,...,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN,3210,RIVERDALE AVENUE,7187085884,10463,3210 RIVERDALE AVENUE | 10463 | 7187085884
5,The Learning Experience,"Riverdale Childcare Experience, Llc",3210,Riverdale Avenue,BRONX,10463,718-708-5884,97738.0,9/28/23,Permitted,...,At time of inspection child care service unabl...,GENERAL,47.25(a)(1),CORRECTED,NaN,3210,RIVERDALE AVENUE,7187085884,10463,3210 RIVERDALE AVENUE | 10463 | 7187085884
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27821,Cornerstone Day Care Center,"Cornerstone Day Care Center, Inc.",289,Lewis Avenue,BROOKLYN,11221,718-574-8300,2267.0,7/8/24,Permitted,...,"Epi auto injector Not provided, Not maintained...",CRITICAL,47.29(c)(1),CORRECTED,Initial Annual Inspection - Reinspection Requi...,289,LEWIS AVENUE,7185748300,11221,289 LEWIS AVENUE | 11221 | 7185748300
27822,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462,718-822-2586,98297.0,10/8/23,Permitted,...,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN,2160,EAST TREMONT AVENUE,7188222586,10462,2160 EAST TREMONT AVENUE | 10462 | 7188222586
27823,Bright Beginnings Early Learning Center,Sidi Inc.,2160,East Tremont Avenue,BRONX,10462,718-822-2586,98297.0,10/8/23,Permitted,...,Enrolled children 6 months to 59 months have N...,CRITICAL,47.25(a)(2)(B),CORRECTED,NaN,2160,EAST TREMONT AVENUE,7188222586,10462,2160 EAST TREMONT AVENUE | 10462 | 7188222586
27826,"The East Chelsea Childrens Workshop, Inc.","The East Chelsea Childrens Workshop, Inc.",17,East 16Th Street,MANHATTAN,10003,212-691-8964,4869.0,7/15/23,Permitted,...,Consent to provide emergency medical care for ...,GENERAL,47..29(b)(1)(A),CORRECTED,Initial Annual Inspection - Passed inspection;...,17,EAST 16TH STREET,2126918964,10003,17 EAST 16TH STREET | 10003 | 2126918964
27827,Children Of America Queens,"Children Of America Queens, Llc",33-06,88 Street,QUEENS,11372,347-730-5438,103774.0,8/23/24,Permitted,...,Constant and competent supervision provided by...,PUBLIC HEALTH HAZARD,47.23(a),CORRECTED,Compliance Inspection of Open Violations - Rei...,33-06,88 STREET,3477305438,11372,33-06 88 STREET | 11372 | 3477305438

In [9]:
#Manually checking instances where there's diff center names of the same location and phone number. If the daycare is the same, merge
multi_name_sites = (
    Violations.groupby(["Building", "Street", "Phone"])
    .agg(
        n_names=("Center Name", "nunique"),
        center_names=("Center Name", lambda x: sorted(set(x))),
        borough=("Borough", "first"),
        zipcode=("ZipCode", "first"))
    .reset_index())

# Only keep sites with multiple names
multi_name_sites = multi_name_sites[
    multi_name_sites["n_names"] > 1]
for _, row in multi_name_sites.head(100).iterrows():
    print(f"\nAddress: {row['Building']} {row['Street']}")
    print(f"Phone: {row['Phone']}")
    print("Center Names:")
    for name in row["center_names"]:
        print(f"  - {name}")

#all instances are the same

Address: 1 Jamaica Center Plaza
Phone: 718-557-5520
Center Names:
  - Imagine Early Learning Centers, Llc
  - Jamaica Kids Infant/Toddler

Address: 1068 Fulton Street
Phone: 718-676-0080
Center Names:
  - Bumblebees Ph Inc.
  - Bumblebees R Us, Inc.

Address: 111A 11Th Avenue
Phone: 212-336-6500
Center Names:
  - Chelsea Piers L. P.
  - Chelsea Piers L.P.

Address: 112-18 Springfield Blvd
Phone: 718-527-5932
Center Names:
  - The Nurturing Academy  Infant/Toddler
  - The Nurturing Center Preschool

Address: 125 Broad Street
Phone: 212-487-9035
Center Names:
  - Bright Horizons Children'S Center, Inc.
  - Bright Horizons Children'S Centers  Llc

Address: 1266 Prospect Avenue
Phone: 718-633-3979
Center Names:
  - Chai Tots Preschool  Of Windsor Terrace (Preschool )
  - Chai Tots Preschool Of Windsor Terrace (Toddler)

Address: 1271 Avenue Of The Americas
Phone: 212-767-4123
Center Names:
  - Bright Horizons Children'S Center
  - Bright Horizons Children'S Centers

Address: 1330 5Th Avenue
Phone: 212-444-1177
Center Names:
  - Sunshine Day Care Of East Harlem  Llc
  - Sunshine Daycare Of East Harlem Llc

Address: 1362 Jerome Avenue
Phone: 718-590-4615
Center Names:
  - Beanstalk Child Care Academy
  - Beanstalk Childcare Academy

Address: 1420 Burke Avenue
Phone: 347-947-3171
Center Names:
  - Little Stars Three, Inc
  - Little Stars Three, Inc.

Address: 145 Rutledge Street
Phone: 718-809-5852
Center Names:
  - Little Munchkins Playgroup 56 Inc
  - Little Munchkins Playgroup 56 Inc.

Address: 1466 Manor Road
Phone: 718-475-5265
Center Names:
  - Jewish Community  Center Of Staten Island, Incorporated
  - Jewish Community Center Of Staten Island, Incorporated

Address: 1637 45Th Street
Phone: 718-871-7432
Center Names:
  - Kinderland Da Care, Inc.
  - Kinderland Day Care Inc.

Address: 17-Feb 51 Avenue
Phone: 718-786-2273
Center Names:
  - Brighter Babies I -Infant Toddler
  - Brighter Babies Inc.

Address: 1701 Nereid Avenue
Phone: 718-324-8300
Center Names:
  - All Seasons Day Care, Llc
  - All Seasons Day Nursery Infant/Toddler

Address: 175 Kent Avenue
Phone: 718-302-1113
Center Names:
  - Bright Horizons At Kent Avenue
  - Bright Horizons Children'S Center Llc.

Address: 175-44 Mayfield Road
Phone: 718-658-1563
Center Names:
  - All My Children Day Care
  - All My Children Day Care & Nursery School

Address: 1770 Davidson Avenue
Phone: 347-789-3091
Center Names:
  - Little Scholars Early Development Center
  - Little Scholars Early Development Center, Llc

Address: 1774 58Th Street
Phone: 718-234-6100
Center Names:
  - Talmud Torah Ohr Moshe
  - Yeshiva Birches Moshe

Address: 1859 Richmond Avenue
Phone: 718-982-0550
Center Names:
  - Big Birds Playhouse Corp.
  - Big Birds Playhouse, Corp

Address: 190 S 1St St
Phone: 347-464-0490
Center Names:
  - Guidepost Fic B Llc.
  - Guidepost Montessori

Address: 1925 Bathgate Avenue
Phone: 718-466-1604
Center Names:
  - Sharon  Baptist  Head Start - Center 4 (Delegate Program)
  - Sharon Baptist Head Start - Grantee

Address: 2 South End Avenue
Phone: 212-786-1688
Center Names:
  - Metrokids Cradle ( South End)  Inc
  - Metrokids Cradle ( South End) Inc

Address: 2-Nov Clintonville Street
Phone: 718-767-6655
Center Names:
  - Precious Moments Day Care Center, Inc.
  - Precious Moments Day Care Center.,Inc.

Address: 200 Boscombe Avenue
Phone: 718-966-8695
Center Names:
  - Gateway Academy
  - Gateway Church

Address: 2007 Linden Boulevard
Phone: 718-257-7555
Center Names:
  - Strawberry Patch Day Care  Inc.
  - Strawberry Patch Day Care Center, Inc.

Address: 21 Snyder Avenue
Phone: 718-940-7700
Center Names:
  - Beginning Steps Day Care
  - Beginning Steps Infant Day Care, Llc

Address: 212-43 Jamaica Avenue
Phone: 718-776-7690
Center Names:
  - Helping Hand Academy
  - Helping Hand Daycare Annex 11 (Swing Space)

Address: 2150 Benson Avenue
Phone: 718-265-4477
Center Names:
  - American-European Child Care Day Care Center
  - European Child Care Day Care Center, Inc.

Address: 2211 Coney Island Avenue
Phone: 718-375-2002
Center Names:
  - Elite Kids Services Inc.
  - Elite Kids Services, Inc

Address: 2249 East 21St Street
Phone: 718-676-0420
Center Names:
  - Blue'S Clue'S Dc ,Inc.
  - Blue'S Clue'S Dc, Inc.

Address: 228 Bushwick Avenue
Phone: 347-689-2222
Center Names:
  - Creative Academy
  - Creative Academy Of Ny Infant/Toddler

Address: 2380 Marion Avenue
Phone: 718-329-6023
Center Names:
  - Round The Clock Nursery
  - Urban Concepts Of New York, Round The Clock Nursery, Inc

Address: 2433 Ocean Parkway
Phone: 718-648-6100
Center Names:
  - Ahi Ezer Early Childhood Corp.
  - Ahi Ezer Preschool

Address: 250 Utica Avenue
Phone: 718-953-9011
Center Names:
  - Bka Of Ny Llc
  - Brooklyn Kids Academy

Address: 258 West 26Th Street
Phone: 212-366-4365
Center Names:
  - Bright Horizons Children'S Centers Llc
  - Bright Horizons Children'S Centers, Llc

Address: 2848 Brighton 7Th Street
Phone: 718-975-3232
Center Names:
  - Tiny Bumblebees Day Care Infant/Toddler
  - Tiny Bumblebees, Inc.

Address: 2975 Independence Avenue
Phone: 718-601-1300
Center Names:
  - Happy Days At Riverdale
  - Renanim Manhattan, Inc.

Address: 30-11 21    Street
Phone: 718-683-4502
Center Names:
  - Bright  Start Child Learning Center, Inc
  - Bright Start Child Learning Center, Inc

Address: 311 Greenwich  Street
Phone: 212-962-1316
Center Names:
  - Kindercare Education At Work  Llc
  - Kindercare Education At Work Llc

Address: 3141 East Tremont Avenue
Phone: 718-829-3067
Center Names:
  - Tender Year Childcare, Inc.
  - Tender Years Childcare Inc.

Address: 3212 Church Avenue
Phone: 718-287-6200
Center Names:
  - Candy Kid'S Day Care Center, Llc
  - Candy Kids Day Care Center, Llc

Address: 3220 Arlington Avenue
Phone: 718-884-0020
Center Names:
  - Bedrock Preschool
  - Bedrock Preschool (P/S)

Address: 33-25 Parsons Blvd.
Phone: 718-888-9499
Center Names:
  - Ka Of Flushing, Inc.
  - Ka Of Flushing,Inc

Address: 334 Milford Street
Phone: 718-277-2003
Center Names:
  - Blake-Milford Day Care Center-I/T
  - Blake-Milford Day Care Center-P/S

Address: 3415 Neptune Avenue
Phone: 718-676-7610
Center Names:
  - Five Stars Child Care 2
  - Five Stars Child Care Ii, Inc.

Address: 345 Adams Street
Phone: 718-488-7770
Center Names:
  - Bright Horizons At Adams Street
  - Bright Horizons Children'S Center, Llc.

Address: 409 East 60Th Street
Phone: 212-750-4534
Center Names:
  - Bright Horizons  Children'S Centers, Llc
  - Bright Horizons Children'S Centers, Llc

Address: 4105 Church Avenue
Phone: 718-856-1100
Center Names:
  - Inner Force Kids Corp.
  - Inner Force Kids Corp. (I/T)

Address: 416 Willis Avenue
Phone: 718-989-9804
Center Names:
  - Sunshine Day Care
  - Sunshine Learning Center

Address: 42-09 28Th Street
Phone: 718-361-6414
Center Names:
  - Bright Horizons @ Long Island City
  - Bright Horizons At Long Island City

Address: 423 East 23 Street
Phone: 212-951-3435
Center Names:
  - Imagine Early Learning Center, Llc
  - Imagine Early Learning Centers, Llc

Address: 435 East 70 Street
Phone: 212-746-6543
Center Names:
  - Bright Horizons  Children'S Centers Llc
  - Bright Horizons Children'S Centers, Llc

Address: 44 Market  Street
Phone: 212-346-9868
Center Names:
  - Metrokids Cradle ( South End) Inc
  - Metrokids Cradle (South End) Inc

Address: 440 Lenox Road
Phone: 718-221-6160
Center Names:
  - The Children'S Center @ Suny Brooklyn - P/S
  - The Children'S Center At Suny Brooklyn

Address: 475 Grand Concourse
Phone: 718-518-4176
Center Names:
  - Hostos Community College Children'S Center
  - Hostos Community College Children'S Center, Inc.

Address: 495 East 158Th Street
Phone: 718-401-0100
Center Names:
  - Bronx Sky Child Care Center, Inc.
  - Bronx Sky Child Care Inc

Address: 5202 13 Avenue
Phone: 718-436-6868
Center Names:
  - Project Social Care Head Start
  - Yeshiva Chaim V ' Shulem

Address: 556 5Th Avenue
Phone: 718-768-4873
Center Names:
  - Park Slope Schoolhouse Child Care Center , Inc. Infant/Toddler
  - Park Slope Schoolhouse Child Care Center, Inc.

Address: 559 East Tremont Ave
Phone: 718-299-2275
Center Names:
  - Bronx  Day Care Center, Inc.
  - Bronx Day Care Center

Address: 576 Gates Avenue
Phone: 718-452-9740
Center Names:
  - Sunshine Nursery & Day Care Center - Infant
  - Sunshine Nursery And Day Care Center

Address: 578 E 138Th St
Phone: 917-635-9709
Center Names:
  - A Kids Space To Dream
  - A Kids Space To Dream Childcare

Address: 609 East 156Th Street
Phone: 347-926-5400
Center Names:
  - Northside Center For Child Development - Bronx Early Head Start
  - Northside Center For Child Development-Bronx Early Headstart

Address: 610 West 112 Street
Phone: 212-875-4412
Center Names:
  - Bank Street College Family Center
  - The Bank Street College Of Education

Address: 63-08 69 Place
Phone: 718-381-7777
Center Names:
  - Books & Rattles, Inc.
  - Books And Rattles, Inc.

Address: 636-640 Bedford Avenue
Phone: 718-963-1212
Center Names:
  - Yeshiva Early Head Start
  - Yeshivath Kehilath Yakov, Inc.

Address: 68-02 Metropolitan Avenue
Phone: 718-417-6770
Center Names:
  - Christ The King Community Day Care Infant/Toddler Program
  - Christ The King Continuing Education, Inc.

Address: 75-02 51 Avenue
Phone: 718-899-1532
Center Names:
  - Books & Rattles, Inc.
  - Books And Rattles, Inc.

Address: 76 Lorraine Street
Phone: 718-858-8111
Center Names:
  - Bubble Bees Day Care - Preschool
  - Bubble Bees Daycare, Llc.

Address: 7817-25 3 Avenue
Phone: 718-680-6566
Center Names:
  - Tutor Time Learning Centers, Llc
  - Tutor Time Learning Centers, Llc.

Address: 787A Washington Avenue
Phone: 718-623-2900
Center Names:
  - Sunflower Playhouse
  - Sunflower Playhouse Corp.

Address: 812 Myrtle Avenue
Phone: 718-596-3632
Center Names:
  - Simche Kinder Inc
  - Simche Kinder Inc.

Address: 823 Classon  Avenue
Phone: 718-783-2337
Center Names:
  - Bumblebees -R-Us Inc.
  - Bumblebees- R- Us, Inc.

Address: 83-38 Cornish Avenue
Phone: 718-859-3311
Center Names:
  - B'Above Worldwide Institute, Inc.
  - Babove Worldwide Institute

Address: 84-15 Beverly Road
Phone: 718-850-2934
Center Names:
  - Sholom  Sholom  Inc
  - Sholom Sholom Inc.

Address: 852 Classon Avenue
Phone: 718-399-3979
Center Names:
  - Chai Tots Preschool Of Prospect Heights
  - Chai Tots Preschool Of Prospect Heights ( I/T)

Address: 882 Fulton St
Phone: 929-227-3100
Center Names:
  - Shining Smiles Daycare 1 Inc.
  - Shining Smiles Daycare I Inc.

Address: 888 Main Street
Phone: 212-750-5301
Center Names:
  - Bright Horizons  Children'S Centers Llc
  - Bright Horizons Children'S Center

Address: 900 Lenox Road
Phone: 718-618-7330
Center Names:
  - Einstein Daycare Inc
  - Einstein Daycare Inc.

Address: 91-10 146 Street
Phone: 718-468-9000
Center Names:
  - Sunshine Developmental School
  - Sunshine School, Llc

Address: 910 9Th Avenue
Phone: 212-399-3919
Center Names:
  - Bright Horizons Children'S Center Llc
  - Bright Horizons Children'S Centers Llc

Address: 950 Baychester Avenue
Phone: 718-320-3902
Center Names:
  - Innovation Garden
  - Sbcc

Address: 99-17 63 Road
Phone: 718-275-0204
Center Names:
  - Fairy Tale Day Care, Inc.
  - Fairytale Day Care Inc.

Address: 992 Gates Avenue
Phone: 718-443-6463
Center Names:
  - Good Samaritan Fulton Day Care Center - Infant/Toddler
  - Good Samaritan Fulton Day Care Center-Preschool

In [10]:
""" Deduplicate same violation at same physical site/date/code/summary:
So I only want to count a violation once if it happened at the same site, same date, same regulation and health code
"""

Violations_deduped = Violations.drop_duplicates(
    subset=[
        "Center_Site_ID",
        "Inspection Date",
        "Regulation Summary",
        "Health Code Sub Section"]).copy()

# Count how many times each unique violation appeared at each physical site
code_counts = (
    Violations_deduped
    .groupby([
        "Center_Site_ID",
        "Health Code Sub Section",
        "Regulation Summary"])
    .size()
    .reset_index(name="times_seen"))

# Repeat instances beyond first occurrence
code_counts["recurrence_score"] = (
    code_counts["times_seen"] - 1 ).clip(lower=0)

# Did this violation type recur?
code_counts["did_repeat"] = (
    code_counts["times_seen"] >= 2)


#Create a lookup from the deduped data for violation category
category_lookup = (
    Violations_deduped
    .assign(
        Violation_Category_Clean=(
            Violations_deduped["Violation Category"].fillna("BLANK").str.strip().str.upper()))
    .drop_duplicates(

        subset=[
            "Center_Site_ID",
            "Health Code Sub Section",
            "Regulation Summary"])
        
    [[      "Center_Site_ID",
            "Health Code Sub Section",
            "Regulation Summary",
            "Violation_Category_Clean"
        ]])

code_counts = code_counts.merge(
    category_lookup,
    on=[
        "Center_Site_ID",
        "Health Code Sub Section",
        "Regulation Summary"
    ],
    how="left")

# Count ALL deduped violations per center
total_violations = (
    Violations_deduped
    .groupby("Center_Site_ID")
    .size()
    .reset_index(name="total_violations"))

# Find the most repeated violation per center
top_repeat_violation = (
    code_counts
    .sort_values(
        ["Center_Site_ID", "times_seen"],
        ascending=[True, False])
    .drop_duplicates("Center_Site_ID")
    [ [
            "Center_Site_ID",
            "Regulation Summary",
            "times_seen"  ] ]
    .rename(columns={
        "Regulation Summary": "top_repeat_violation",
        "times_seen": "max_times_same_violation_seen"}))

# Count recurrence score by violation category. Ex: Critical issue seen 3 times = recurrence_score 2

recurrence_by_category = (
    code_counts
    .pivot_table(
        index="Center_Site_ID",
        columns="Violation_Category_Clean",
        values="recurrence_score",
        aggfunc="sum",
        fill_value=0)
    .reset_index()
)

recurrence_by_category = recurrence_by_category.rename(columns={
    "CRITICAL": "recurring_critical_violations",
    "GENERAL": "recurring_general_violations",
    "PUBLIC HEALTH HAZARD": "recurring_public_health_violations",
    "BLANK": "recurring_blank_category_violations"
})

# Summarize center-level metrics
center_recurrence = (
    code_counts
    .groupby("Center_Site_ID")
    .agg(
        recurrence_score=("recurrence_score", "sum"),
        repeated_violation_types=("did_repeat", "sum"),
        total_violation_types=("Regulation Summary", "count"))
    .reset_index())


# Count violations by category per center
violation_category_counts = (
    Violations_deduped
    .assign(
        Violation_Category_Clean=
        Violations_deduped["Violation Category"]
        .fillna("BLANK")
        .str.strip()
        .str.upper())
    .pivot_table(
        index="Center_Site_ID",
        columns="Violation_Category_Clean",
        values="Regulation Summary",
        aggfunc="count",
        fill_value=0)
    .reset_index())

# Rename columns to easier names
violation_category_counts = (
    violation_category_counts.rename(columns={
        "CRITICAL": "critical_violations",
        "GENERAL": "general_violations",
        "PUBLIC HEALTH HAZARD": "public_health_violations",
        "BLANK": "blank_category_violations"})
)

# Merge category counts into center table
center_recurrence = center_recurrence.merge(
    violation_category_counts,
    on="Center_Site_ID",
    how="left"
)

# Fill missing with 0
category_cols = [
    "critical_violations",
    "general_violations",
    "public_health_violations",
    "blank_category_violations"]

for col in category_cols:
    if col in center_recurrence.columns:
        center_recurrence[col] = (
            center_recurrence[col]
            .fillna(0)
            .astype(int))

# Merge in total violations
center_recurrence = center_recurrence.merge(
    total_violations,
    on="Center_Site_ID",
    how="left")

# Merge in top repeated violation
center_recurrence = center_recurrence.merge(
    top_repeat_violation,
    on="Center_Site_ID",
    how="left")

site_lookup = (
    Violations
    .groupby("Center_Site_ID")
    .agg(
        # Combine all center names at same site
        center_names=(
            "Center Name",
            lambda x: " / ".join(sorted(set(x)))),
        borough=("Borough", "first"),
        zipcode=("ZipCode", "first"),
        building=("Building", "first"))
    .reset_index())

# Merge readable center info
center_recurrence = center_recurrence.merge(
    site_lookup,
    on="Center_Site_ID",
    how="left")

center_recurrence = center_recurrence.merge(
    recurrence_by_category,
    on="Center_Site_ID",
    how="left")

recurring_category_cols = [
    "recurring_critical_violations",
    "recurring_general_violations",
    "recurring_public_health_violations",
    "recurring_blank_category_violations"]

for col in recurring_category_cols:
    if col in center_recurrence.columns:
        center_recurrence[col] = (
            center_recurrence[col]
            .fillna(0)
            .astype(int))

# Sort descending by biggest repeated single issue
center_recurrence = center_recurrence.sort_values(
    [
        "total_violations",
        "max_times_same_violation_seen",
        "repeated_violation_types",
        "recurrence_score"
    ],
    ascending=False)

center_recurrence.head(50)

,Center_Site_ID,recurrence_score,repeated_violation_types,total_violation_types,blank_category_violations,critical_violations,general_violations,public_health_violations,total_violations,top_repeat_violation,max_times_same_violation_seen,center_names,borough,zipcode,building,recurring_critical_violations,recurring_general_violations,recurring_public_health_violations
917,33-06 88 STREET | 11372 | 3477305438,23,10,27,0,18,27,5,50,Staff and volunteers obtain documentation show...,6,Children Of America Queens,QUEENS,11372,33-06,6,17,0
669,2380 MARION AVENUE | 10458 | 7183296023,18,10,26,0,18,17,9,44,At time of inspection floors/walls ceilings we...,4,Round The Clock Nursery / Urban Concepts Of Ne...,BRONX,10458,2380,8,8,2
313,1465 WEBSTER AVENUE | 10456 | 7186817040,13,8,31,0,22,11,11,44,At time of inspection hand wash sinks are Not ...,4,Beanstalk Child Care Academy,BRONX,10456,1465,9,1,3
924,331 EAST 150 STREET | 10451 | 7182920812,15,10,26,0,21,12,8,41,At time of inspection floors/walls ceilings we...,5,"Nyc Early Learning Company, Inc / Nyc Early Le...",BRONX,10451,331,8,6,1
1354,63-08 69 PLACE | 11379 | 7183817777,18,9,22,0,20,15,5,40,Staff and volunteers obtain documentation show...,5,"Books & Rattles, Inc. / Books And Rattles, Inc.",QUEENS,11379,63-08,9,8,1
1658,950 WESTCHESTER AVENUE | 10459 | 7189915465,14,8,23,0,18,11,8,37,At time of inspection hand wash sinks are Not ...,5,Beanstalk Child Care Academy,BRONX,10459,950,9,4,1
591,2160 EAST TREMONT AVENUE | 10462 | 7188222586,8,8,29,0,19,13,5,37,Qualified Group Teacher Not designated to cove...,2,Bright Beginnings Early Learning Center,BRONX,10462,2160,4,3,1
884,3141 EAST TREMONT AVENUE | 10461 | 7188293067,11,7,25,0,9,14,13,36,Staff and volunteers obtain documentation show...,4,"Tender Year Childcare, Inc. / Tender Years Chi...",BRONX,10461,3141,1,5,5
1512,800 CONCOURSE VILLAGE EAST | 10451 | 7187422370,19,8,12,0,16,14,1,31,At time of inspection child care service facil...,7,Highbridge Advisory Council Marshall England E...,BRONX,10451,800,11,8,0
968,3480 THIRD AVENUE | 10456 | 7184848777,9,5,22,0,10,18,3,31,At time of inspection floors/walls ceilings we...,5,Habitot,BRONX,10456,3480,1,8,0
1519,810 EAST 152 STREET | 10455 | 6468564890,12,10,19,0,14,15,2,31,Child care service staff identified/acting as ...,3,Blended Family,BRONX,10455,810,5,7,0
1370,64-41 UTOPIA PKWY. | 11365 | 7184800100,13,9,18,0,9,15,7,31,Teaching and supervisory staff trained in abus...,3,Jewish Institute Of Queens Preschool,QUEENS,11365,64-41,5,6,2
534,2007 LINDEN BOULEVARD | 11207 | 7182577555,14,6,16,0,13,11,6,30,At time of inspection it was determined that c...,6,Strawberry Patch Day Care Inc. / Strawberry P...,BROOKLYN,11207,2007,7,6,1
832,2975 INDEPENDENCE AVENUE | 10463 | 7186011300,10,7,20,0,17,10,3,30,A corrective action plan was Not submitted by ...,4,"Happy Days At Riverdale / Renanim Manhattan, Inc.",BRONX,10463,2975,8,2,0
862,3041 KINGSBRIDGE AVENUE | 10463 | 7185491525,10,7,20,0,15,13,2,30,Staff and volunteers obtain documentation show...,3,"Spuyten Duyvil Preschool, Inc.",BRONX,10463,3041,4,6,0
816,2901 WHITE PLAINS ROAD | 10467 | 7186533714,7,5,22,0,10,13,6,29,At time of inspection floors/walls ceilings we...,3,Beanstalk Childcare Academy,BRONX,10467,2901,1,5,1
1657,950 BAYCHESTER AVENUE | 10475 | 7183203902,6,4,22,0,14,13,1,28,At time of inspection floors/walls ceilings we...,4,Innovation Garden / Sbcc,BRONX,10475,950,3,3,0
503,195-05 LINDEN BOULEVARD | 11412 | 7187233967,10,7,18,0,15,11,2,28,Staff and volunteers obtain documentation show...,3,"Montessori Progressive Learning Center, Inc.",QUEENS,11412,195-05,6,4,0
110,115-50 221 STREET | 11411 | 7185270123,7,6,21,0,8,14,6,28,Failure to install approved window guards or l...,3,Sacred Heart School,QUEENS,11411,115-50,0,5,2
16,100-120 EAST MOUNT EDEN AVENUE | 10452 | 71868...,13,5,14,0,10,15,2,27,At time of inspection floors/walls ceilings we...,8,Mid Bronx Ccrp Early Childhood Center,BRONX,10452,100-120,4,9,0
1034,3950 LACONIA AVENUE | 10466 | 7185470000,8,5,18,0,12,10,4,26,Child care service Not free of pests or mainta...,4,Laconia Daycare Center And Infant Care Inc,BRONX,10466,3950,5,3,0
1155,4545 INDEPENDENCE AVENUE | 10471 | 7187960335,9,8,17,0,12,8,6,26,Pass key identification or other security devi...,3,Riverdale Temple,BRONX,10471,4545,5,3,1
1039,4 EAST 90 STREET | 10128 | 2126410260,3,3,23,0,9,13,4,26,Plumbing and plumbing fixtures Not properly co...,2,International Academy Of New York,MANHATTAN,10128,4,0,3,0
231,1332 FULTON AVENUE | 10456 | 7186350474,14,6,11,0,12,12,1,25,Children enrolled in school-based child care p...,5,The Gloria Alston Children'S Learning Center (...,BRONX,10456,1332,8,6,0
551,2075 JEROME AVENUE | 10453 | 7187692698,6,3,19,0,8,12,5,25,At time of inspection floors/walls ceilings we...,5,City Pro Group,BRONX,10453,2075,1,5,0
130,118-46 RIVERTON STREET | 11412 | 7189780800,6,5,19,0,9,12,4,25,Staff and volunteers obtain documentation show...,3,Quick Start D.C.C. Inc.,QUEENS,11412,118-46,2,4,0
1036,3952 THIRD AVENUE | 10457 | 3479634073,9,9,16,0,13,11,1,25,Child care service providing care without a st...,2,Bright Future Kiddie 4,BRONX,10457,3952,5,4,0
442,1794 FIRST AVENUE | 10128 | 2128769200,4,4,21,0,7,14,4,25,At time of inspection hallways and other means...,2,Eisman Day Nursery,MANHATTAN,10128,1794,0,3,1
1459,75-02 51 AVENUE | 11373 | 7188991532,10,6,14,0,7,14,3,24,Staff and volunteers obtain documentation show...,4,"Books & Rattles, Inc. / Books And Rattles, Inc.",QUEENS,11373,75-02,2,8,0
782,2778 BRUCKNER BOULEVARD | 10465 | 7188634925,9,8,15,0,7,14,3,24,Child care service staff identified/acting as ...,3,"These Our Treasures, Inc.",BRONX,10465,2778,3,5,1
1035,3952 3RD AVE | 10457 | 3479634073,7,6,16,0,12,10,1,23,At time of inspection floors/walls ceilings we...,3,Bright Future Kiddie 4,BRONX,10457,3952,3,4,0
967,3471 FENTON AVENUE | 10469 | 7186555361,5,5,18,0,10,11,2,23,Enrolled children 6 months to 59 months have N...,2,"J.A.D.E. Multi Family Circle Center, Inc.",BRONX,10469,3471,3,2,0
1462,75-43 PARSONS BLVD | 11366 | 7183803683,5,5,18,0,10,6,7,23,Child care service operating without a permit;...,2,Asian American Coalition For Education,QUEENS,11366,75-43,2,1,2
1505,80 RIVERSIDE BOULEVARD | 10069 | 2129571234,4,4,19,0,9,12,2,23,Child care service staff identified/acting as ...,2,La Maternelle Llc,MANHATTAN,10069,80,3,1,0
1233,5215 CHURCH AVENUE | 11203 | 9292342451,4,2,18,0,12,6,4,22,At time of inspection it was determined that c...,4,Magic Kingdom,BROOKLYN,11203,5215,3,1,0
1638,924 TELLER AVENUE | 10451 | 7182983930,4,2,18,0,9,8,5,22,Staff and volunteers obtain documentation show...,4,Luminous Child Care,BRONX,10451,924,0,3,1
135,1185 EAST 223RD STREET | 10466 | 6466624708,6,5,16,0,12,8,2,22,At time of inspection floors/walls ceilings we...,3,Light And Bright Early Learning Center,BRONX,10466,1185,3,2,1
875,31-57 31ST ST | 11106 | 7182041352,4,3,18,0,7,12,3,22,Staff and volunteers obtain documentation show...,3,Tle,QUEENS,11106,31-57,0,3,1
1101,423 EAST 138 STREET | 10454 | 6466603214,10,7,11,0,8,13,0,21,School-based child care staff observed caring ...,5,Nyc Montessori Charter School,BRONX,10454,423,3,7,0
1055,4020 EAST TREMONT AVENUE | 10465 | 7182395275,4,3,17,0,13,7,1,21,At time of inspection floors/walls ceilings we...,3,"Gko Group, Inc.",BRONX,10465,4020,1,3,0
30,102-35 63 ROAD | 11375 | 7188964444,3,3,18,0,8,9,4,21,At time of inspection it was determined that c...,2,Beth Jacob Jewish Ed. Ctr,QUEENS,11375,102-35,1,2,0
1633,92-10 217 STREET | 11428 | 7184653252,6,3,14,0,5,12,3,20,Appropriate outdoor play area Not provided or ...,4,The Evangelical Lutheran Church Of The Redeemer,QUEENS,11428,92-10,0,5,1
1085,414 MORRIS AVENUE | 10451 | 7184014242,5,3,15,0,9,6,5,20,At time of inspection floors/walls ceilings we...,4,East Side Settlement House Head Start/ Day Care,BRONX,10451,414,2,3,0
1062,4063 EDSON AVENUE | 10466 | 7189940604,8,6,12,0,8,7,5,20,Teacher to child ratios and group size maintai...,3,"Little Stars School, Inc. / Little Stars",BRONX,10466,4063,4,2,2
1409,68-05 64TH PLACE | 11385 | 7188083407,6,5,14,0,9,10,1,20,At time of inspection records of enrolled chil...,3,"Once Upon A Child Day Care, Llc",QUEENS,11385,68-05,3,3,0
1517,81-10 35 AVENUE | 11372 | 7184570429,5,3,15,0,6,12,2,20,At time of inspection it was determined that c...,3,82Nd Street Academics,QUEENS,11372,81-10,0,5,0
1292,578 E 138TH ST | 10454 | 9176359709,3,3,17,0,10,4,6,20,Teacher to child ratios and group size maintai...,2,A Kids Space To Dream / A Kids Space To Dream ...,BRONX,10454,578,2,0,1
1047,40-69 94 STREET | 11373 | 7188039788,2,2,18,0,8,8,4,20,Enrolled children 6 months to 59 months have N...,2,Moving Up Children Center,QUEENS,11373,40-69,1,1,0
1009,378 EAST 151 STREET | 10455 | 7185854843,7,6,12,0,10,7,2,19,Water Not tested for lead as required. Elevate...,3,Immaculate Conception 151St Preschool,BRONX,10455,378,4,3,0
1669,98-25 HORACE HARDING EXPRESSWAY | 11368 | 7184...,4,3,15,0,8,6,5,19,At time of inspection floors/walls ceilings we...,3,Happy Dragon Children Learning Center,QUEENS,11368,98-25,1,2,1

In [11]:
# Get top 50 rows
top100_centers = center_recurrence.head(100)

# Export to Excel
top100_centers.to_excel(
    "top100_repeat_daycare_centers.xlsx",
    index=False)

In [12]:
#doing some QA on the data analyzed

# Get top 10 physical center sites by recurrence score
top10_sites = center_recurrence.head(10)["Center_Site_ID"].tolist()

# Pull all deduped violations for only those top 5 sites
top10_violation_detail = (
    Violations_deduped[
        Violations_deduped["Center_Site_ID"].isin(top10_sites)]
    .merge(
        site_lookup,
        on="Center_Site_ID",
        how="left",
        suffixes=("", "_site")
    )
    .sort_values(
        ["Center_Site_ID", "Inspection Date", "Health Code Sub Section"],
        ascending=[True, True, True]
    ))

# Select useful QA columns
top10_violation_detail = top10_violation_detail[
    [
        "Center_Site_ID",
        "center_names",
        "borough",
        "zipcode",
        "building",
        "Inspection Date",
        "Health Code Sub Section",
        "Regulation Summary",
        "Violation Category",
        "Violation Status",
        "Inspection Summary Result"
    ]
]

for site_id in top10_sites:
    site_rows = top10_violation_detail[
        top10_violation_detail["Center_Site_ID"] == site_id
    ]
    
    first = site_rows.iloc[0]
    
    print("\n" + "="*100)
    print(f"Center Site ID: {site_id}")
    print(f"Center Name(s): {first['center_names']}")
    print(f"Address: {first['building']}  {first['borough']} {first['zipcode']}")
    print("="*100)
    
    for _, row in site_rows.iterrows():
        print(f"\nDate: {row['Inspection Date']}")
        print(f"Category: {row['Violation Category']}")
        print(f"Violation: {row['Regulation Summary']}")

#export data to Excel for quality check
top10_violation_detail = top10_violation_detail.sort_values(
    [  "center_names",
        "Inspection Date"])

top10_violation_detail.to_excel(
    "top10_center_site_QA.xlsx",
    index=False)

====================================================================================================
Center Site ID: 33-06 88 STREET | 11372 | 3477305438
Center Name(s): Children Of America Queens
Address: 33-06  QUEENS 11372
====================================================================================================

Date: 2020-08-07 00:00:00
Category: GENERAL
Violation: Child care service staff identified/acting as group teachers do Not meet the required qualifications of the position.

Date: 2020-09-16 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2020-09-16 00:00:00
Category: CRITICAL
Violation: Exits and other egress Not provided with required signage at time of inspection.

Date: 2020-09-16 00:00:00
Category: CRITICAL
Violation: Required food protection procedures were Not implemented at time of inspection. Holder of food protection certificate was Not on site during hours of food preparation activity.

Date: 2020-10-23 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2021-10-07 00:00:00
Category: GENERAL
Violation: Child care service failed to conduct business and employment reference checks of staff/volunteers.

Date: 2021-10-07 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service allows staff to perform their duties that are Not healthy or are incapable of carrying out their duties. Staff medical clearances are Not maintained by child care service.

Date: 2021-10-07 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2021-10-07 00:00:00
Category: CRITICAL
Violation: At time of inspection it was determined that child care service failed to ensure staff received required training within time frames and/or failed to maintain training records.

Date: 2021-10-07 00:00:00
Category: GENERAL
Violation: At time of inspection floors/walls ceilings were observed Not maintained; in disrepair or covered in a toxic finish.

Date: 2021-10-07 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Milk observed stored at a temperature above 41 deg. F at time of inspection. Milk observed stored in child care service beyond the expiration date.

Date: 2021-10-07 00:00:00
Category: CRITICAL
Violation: Child care service fails to store dry goods in insect/rodent proof containers at time of inspection.

Date: 2021-10-15 00:00:00
Category: GENERAL
Violation: Child care service failed to conduct business and employment reference checks of staff/volunteers.

Date: 2021-10-15 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service allows staff to perform their duties that are Not healthy or are incapable of carrying out their duties. Staff medical clearances are Not maintained by child care service.

Date: 2021-10-15 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2021-10-15 00:00:00
Category: CRITICAL
Violation: At time of inspection it was determined that child care service failed to ensure staff received required training within time frames and/or failed to maintain training records.

Date: 2021-10-15 00:00:00
Category: CRITICAL
Violation: All teachers have Not received training in infectious disease control and reporting.

Date: 2021-10-15 00:00:00
Category: CRITICAL
Violation: At time of inspection child care service facility observed Not maintained or in disrepair. Dry sweeping observed in areas occupied by children.

Date: 2021-10-15 00:00:00
Category: CRITICAL
Violation: Exits and other egress Not provided with required signage at time of inspection.

Date: 2021-11-18 00:00:00
Category: GENERAL
Violation: Child care service failed to conduct business and employment reference checks of staff/volunteers.

Date: 2021-11-18 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service allows staff to perform their duties that are Not healthy or are incapable of carrying out their duties. Staff medical clearances are Not maintained by child care service.

Date: 2021-11-18 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2021-11-30 00:00:00
Category: GENERAL
Violation: Child care service failed to conduct business and employment reference checks of staff/volunteers.

Date: 2021-11-30 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service allows staff to perform their duties that are Not healthy or are incapable of carrying out their duties. Staff medical clearances are Not maintained by child care service.

Date: 2021-11-30 00:00:00
Category: CRITICAL
Violation: At time of inspection it was determined that child care service failed to ensure staff received required training within time frames and/or failed to maintain training records.

Date: 2021-12-29 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2021-12-29 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: At time of inspection it was observed that children and staff failed to wash hands after using lavatory, after diaper changing, prior to preparation of food or when else required.

Date: 2022-01-10 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Uncleared staff observed having unsupervised contact with children. Current SCR clearance is over 2 years old. Documents Not available at time of inspection

Date: 2022-01-10 00:00:00
Category: GENERAL
Violation: Child care service failed to conduct business and employment reference checks of staff/volunteers.

Date: 2022-01-10 00:00:00
Category: CRITICAL
Violation: Enrolled children 6 months to 59 months have Not received FDA approved annual influenza immunization by December 31 of the year

Date: 2022-01-10 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service allows staff to perform their duties that are Not healthy or are incapable of carrying out their duties. Staff medical clearances are Not maintained by child care service.

Date: 2022-01-10 00:00:00
Category: CRITICAL
Violation: At time of inspection it was determined that child care service failed to ensure staff received required training within time frames and/or failed to maintain training records.

Date: 2022-02-28 00:00:00
Category: GENERAL
Violation: Written Safety Plan does Not include safe sleep provisions

Date: 2022-06-07 00:00:00
Category: GENERAL
Violation: Child care service fails to conduct and document daily health assessment of incoming children. Individual Not trained to identify disease.

Date: 2022-06-07 00:00:00
Category: GENERAL
Violation: 15 hours of training Not completed in 24 months. At least 5 hours of training Not conducted in each 12 month period. Required topics Not covered.

Date: 2022-07-11 00:00:00
Category: GENERAL
Violation: At time of inspection floors/walls ceilings were observed Not maintained; in disrepair or covered in a toxic finish.

Date: 2022-07-11 00:00:00
Category: CRITICAL
Violation: At time of inspection child care service facility observed Not maintained or in disrepair. Dry sweeping observed in areas occupied by children.

Date: 2022-07-11 00:00:00
Category: GENERAL
Violation: Cots or other sleep equipment Not placed two feet apart or separated by a partition

Date: 2022-08-05 00:00:00
Category: CRITICAL
Violation: Qualified Group Teacher Not designated to cover for Education Director. Permittee failed to Notify Department of separation from service of Education Director

Date: 2022-08-05 00:00:00
Category: GENERAL
Violation: At time of inspection floors/walls ceilings were observed Not maintained; in disrepair or covered in a toxic finish.

Date: 2022-08-05 00:00:00
Category: CRITICAL
Violation: Appropriate child activity Not provided by child care service; unacceptable forms of discipline utilized by staff of child care service.

Date: 2022-08-22 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Constant and competent supervision provided by adequate staff for children and groups of children

Date: 2022-08-22 00:00:00
Category: GENERAL
Violation: Child care service fails to conduct and document daily health assessment of incoming children. Individual Not trained to identify disease.

Date: 2022-08-22 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Emergency medical care Not secured when needed; parents Not Notified immediately.

Date: 2022-08-22 00:00:00
Category: GENERAL
Violation: Clean sheet Not provided for each child

Date: 2022-09-20 00:00:00
Category: CRITICAL
Violation: Child care service observed at time of inspection to be providing care for infants under 12 months of age in groups mixed with older children.

Date: 2022-10-14 00:00:00
Category: CRITICAL
Violation: Training in SIDS, Shaken Baby Syndrome and Safe Sleep practices Not provided to staff

Date: 2022-10-14 00:00:00
Category: CRITICAL
Violation: At time of inspection toxic substances observed improperly stored so as to result in the potential for exposure or contamination of facility surfaces.

Date: 2022-10-14 00:00:00
Category: CRITICAL
Violation: Child care service fails to store dry goods in insect/rodent proof containers at time of inspection.

Date: 2023-03-08 00:00:00
Category: GENERAL
Violation: Child care service staff identified/acting as group teachers do Not meet the required qualifications of the position.

====================================================================================================
Center Site ID: 2380 MARION AVENUE | 10458 | 7183296023
Center Name(s): Round The Clock Nursery / Urban Concepts Of New York, Round The Clock Nursery, Inc
Address: 2380  BRONX 10458
====================================================================================================

Date: 2020-09-04 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service allows staff to perform their duties that are Not healthy or are incapable of carrying out their duties. Staff medical clearances are Not maintained by child care service.

Date: 2020-09-04 00:00:00
Category: GENERAL
Violation: At time of inspection floors/walls ceilings were observed Not maintained; in disrepair or covered in a toxic finish.

Date: 2020-09-04 00:00:00
Category: CRITICAL
Violation: Proper ventilation Not provided or maintained at time of inspection. Indoor air quality nuisance allowed to exist at time of inspection.

Date: 2020-09-04 00:00:00
Category: CRITICAL
Violation: At time of inspection child care service facility observed Not maintained or in disrepair. Dry sweeping observed in areas occupied by children.

Date: 2020-09-25 00:00:00
Category: CRITICAL
Violation: Child care service providing care without a staff member trained in First Aid/CPR on site at time of inspection.

Date: 2020-09-25 00:00:00
Category: GENERAL
Violation: At time of inspection floors/walls ceilings were observed Not maintained; in disrepair or covered in a toxic finish.

Date: 2021-07-02 00:00:00
Category: GENERAL
Violation: Permittee conducted facility renovations and/or modified the terms of the permit without prior approval from DOHMH.

Date: 2021-07-02 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Fingerprint screening Not arranged for current and prospective personnel; Results Not satisfactory or CAP was Not approved

Date: 2021-07-02 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: At time of inspection children were observed occupying space Not previously approved by the Dept of Buildings, FDNY and/or DOHMH.

Date: 2021-08-19 00:00:00
Category: GENERAL
Violation: All staff with potential for unsupervised contact with children including volunteers have Not been cleared

Date: 2021-08-19 00:00:00
Category: CRITICAL
Violation: At time of inspection hand wash sinks are Not supplied with an adequate amount of running water. At time of inspection water temperature exceeded 115 deg Fahrenheit.

Date: 2021-08-19 00:00:00
Category: CRITICAL
Violation: Proper ventilation Not provided or maintained at time of inspection. Indoor air quality nuisance allowed to exist at time of inspection.

Date: 2021-08-19 00:00:00
Category: CRITICAL
Violation: At time of inspection child care service facility observed Not maintained or in disrepair. Dry sweeping observed in areas occupied by children.

Date: 2021-09-15 00:00:00
Category: CRITICAL
Violation: At time of inspection hand wash sinks are Not supplied with an adequate amount of running water. At time of inspection water temperature exceeded 115 deg Fahrenheit.

Date: 2021-10-28 00:00:00
Category: CRITICAL
Violation: Child care service failed to Notify DOHMH within 24 hours of child abuse allegation/indication or record of criminal activity of individuals associated with child care service; serious injury, death or loss of a child.

Date: 2021-10-28 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Permittee fails to maintain list of authorized escort for each child. Permittee released a child to individual Not identified as an authorized escort

Date: 2021-10-28 00:00:00
Category: CRITICAL
Violation: Permittee failed to Notify parent of requirement for authorized escort. Permittee failed to confirm escort is authorized.

Date: 2021-10-29 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Commissioner may order a child care service to close or discontinue operations if the child care service is determined to be operating in a manner or maintaining one or more conditions that constitute an imminent health hazard

Date: 2021-12-02 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Constant and competent supervision provided by adequate staff for children and groups of children

Date: 2021-12-02 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Teacher to child ratios and group size maintained in Group Child Care program

Date: 2021-12-02 00:00:00
Category: CRITICAL
Violation: Proper ventilation Not provided or maintained at time of inspection. Indoor air quality nuisance allowed to exist at time of inspection.

Date: 2021-12-02 00:00:00
Category: CRITICAL
Violation: At time of inspection child care service facility observed Not maintained or in disrepair. Dry sweeping observed in areas occupied by children.

Date: 2021-12-02 00:00:00
Category: CRITICAL
Violation: Child care service Not free of pests or maintains pest harborage conditions at time of inspection.

Date: 2021-12-02 00:00:00
Category: CRITICAL
Violation: At time of inspection it was determined that child care service failed to take any and all necessary action to eliminate potential hazards.

Date: 2022-04-27 00:00:00
Category: GENERAL
Violation: All staff with potential for unsupervised contact with children including volunteers have Not been cleared

Date: 2022-10-04 00:00:00
Category: GENERAL
Violation: Child care service staff identified/acting as group teachers do Not meet the required qualifications of the position.

Date: 2022-10-04 00:00:00
Category: GENERAL
Violation: All staff with potential for unsupervised contact with children including volunteers have Not been cleared

Date: 2022-10-04 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service allows staff to perform their duties that are Not healthy or are incapable of carrying out their duties. Staff medical clearances are Not maintained by child care service.

Date: 2022-10-04 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2022-10-04 00:00:00
Category: GENERAL
Violation: 15 hours of training Not completed in 24 months. At least 5 hours of training Not conducted in each 12 month period. Required topics Not covered.

Date: 2023-02-14 00:00:00
Category: GENERAL
Violation: Staff and volunteers obtain documentation showing immunization with 2 doses measles/mumps, 1 dose rubella, 2 doses varicella and 1 dose Tdap. Medical exemptions only. History of measles, mumps or rubella shall Not replace MMR vaccine except in presence of MMR varicella antibodies.

Date: 2023-02-14 00:00:00
Category: GENERAL
Violation: At time of inspection floors/walls ceilings were observed Not maintained; in disrepair or covered in a toxic finish.

Date: 2023-02-14 00:00:00
Category: CRITICAL
Violation: At time of inspection child care service facility observed Not maintained or in disrepair. Dry sweeping observed in areas occupied by children.

Date: 2023-03-21 00:00:00
Category: CRITICAL
Violation: At time of inspection it was determined that child care service failed to take any and all necessary action to eliminate potential hazards.

Date: 2023-03-27 00:00:00
Category: GENERAL
Violation: At time of inspection floors/walls ceilings were observed Not maintained; in disrepair or covered in a toxic finish.

Date: 2023-03-27 00:00:00
Category: CRITICAL
Violation: At time of inspection child care service failed to provide sufficient number of toilets and sinks for the number of children in attendance.

Date: 2023-03-27 00:00:00
Category: CRITICAL
Violation: At time of inspection it was determined that child care service failed to take any and all necessary action to eliminate potential hazards.

Date: 2023-03-28 00:00:00
Category: CRITICAL
Violation: Child care service or child care service permit applicant failed to Notify DOHMH of child deaths, serious injuries or civil/criminal actions relating to individuals associated with the child care service.

Date: 2023-03-28 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Constant and competent supervision provided by adequate staff for children and groups of children

Date: 2023-03-28 00:00:00
Category: GENERAL
Violation: Incident injury log of accidents illness and epi auto injector use Not provided, Not maintained and Not available upon request

Date: 2023-03-28 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Services fail to install interior fire alarms and/or sprinklers where required.

Date: 2023-03-29 00:00:00
Category: PUBLIC HEALTH HAZARD
Violation: Services fail to install interior fire alarms and/or sprinklers where required.

Date: 2023-03-31 00:00:00
Category: GENERAL
Violation: At time of inspection it was determined that child care service failed to maintain children's daily attendance records.

Date: 2023-04-17 00:00:00
Category: GENERAL

In [13]:
#I forgot to look at the total number of childcare centers in this data. Here it is:

All_Centers = pd.read_csv(
    "DOHMH_Childcare_Center_Inspections_(Historical)_20260511.csv")

# Keep same age ranges as story
allowed_ages = [
    "0 YEARS - 2 YEARS",
    "2 YEARS - 5 YEARS",
    "3 YEARS - 5 YEARS"]

All_Centers = All_Centers[
    All_Centers["Age Range"].isin(allowed_ages)
].copy()

# Recreate same Center_Site_ID logic
All_Centers["Building_clean"] = (
    All_Centers["Building"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True))

All_Centers["Street_clean"] = (
    All_Centers["Street"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", " ", regex=True))

All_Centers["Phone_clean"] = (
    All_Centers["Phone"]
    .astype(str)
    .str.replace(r"\D", "", regex=True)
    .str.strip())

All_Centers["ZipCode_clean"] = (
    pd.to_numeric(
        All_Centers["ZipCode"],
        errors="coerce")
    .astype("Int64")
    .astype(str))

All_Centers["Center_Site_ID"] = (
    All_Centers["Building_clean"]
    + " "
    + All_Centers["Street_clean"]
    + " | "
    + All_Centers["ZipCode_clean"]
    + " | "
    + All_Centers["Phone_clean"])

# Summary counts
total_citywide_centers = (
    All_Centers["Center_Site_ID"]
    .nunique())

centers_with_1plus_violations = (
    Violations_deduped["Center_Site_ID"]
    .nunique())

centers_with_1plus_recurring = (
    center_recurrence[
        center_recurrence["recurrence_score"] >= 1
    ]["Center_Site_ID"]
    .nunique())

centers_with_5plus_recurring = (
    center_recurrence[
        center_recurrence["recurrence_score"] >= 3
    ]["Center_Site_ID"]
    .nunique())

print(f"Total childcare centers citywide (0–5): {total_citywide_centers:,}")
print(f"Centers with 1+ violations: {centers_with_1plus_violations:,}")
print(f"Centers with 1+ recurring violations: {centers_with_1plus_recurring:,}")
print(f"Centers with 3+ recurring violations: {centers_with_5plus_recurring:,}")

Total childcare centers citywide (0–5): 2,225
Centers with 1+ violations: 1,787
Centers with 1+ recurring violations: 515
Centers with 3+ recurring violations: 160

In [18]:
#Export all citywide childcare centers (0–5), One row per physical site


# Add recurrence + violation metrics to all citywide centers
all_citywide_centers_with_metrics = all_citywide_centers.merge(
    center_recurrence[
        [
            "Center_Site_ID",
            "recurrence_score",
            "total_violations",
            "repeated_violation_types",
            "max_times_same_violation_seen"
        ]
    ],
    on="Center_Site_ID",
    how="left"
)

# Centers with no violations will be blank after merge, so convert to 0
metric_cols = [
    "recurrence_score",
    "total_violations",
    "repeated_violation_types",
    "max_times_same_violation_seen"
]

all_citywide_centers_with_metrics[metric_cols] = (
    all_citywide_centers_with_metrics[metric_cols]
    .fillna(0)
    .astype(int)
)

# Clean hidden Excel characters
all_citywide_centers_with_metrics = all_citywide_centers_with_metrics.replace(
    r"[\x00-\x1F]+",
    "",
    regex=True
)

# Create all_citywide_centers first
all_citywide_centers = (
    All_Centers
    .groupby("Center_Site_ID")
    .agg(
        center_names=("Center Name", lambda x: " / ".join(sorted(set(x)))),
        legal_names=("Legal Name", lambda x: " / ".join(sorted(set(x)))),
        borough=("Borough", "first"),
        zipcode=("ZipCode", "first"),
        building=("Building", "first"),
        street=("Street", "first"),
        phone=("Phone", "first"),
        status=("Status", "first"),
        permit_expiration=("Permit Expiration", "first")
    )
    .reset_index()
)
"""
# Export
all_citywide_centers_with_metrics.to_excel(
    "all_citywide_childcare_centers_0to5_with_metrics.xlsx",
    index=False)"""

NameError: name 'all_citywide_centers' is not defined

In [19]:
# Sort centers by recurrence score
ranked_centers = center_recurrence.sort_values(
    "recurrence_score",
    ascending=False).copy()

# Only centers with at least 1 violation
centers_with_violations = ranked_centers[
    ranked_centers["total_violations"] >= 1].copy()
def bronx_share(df, label):
    total = len(df)
    bronx = (df["borough"].str.upper() == "BRONX").sum()
    pct = bronx / total if total > 0 else 0
    return {
        "Group": label,
        "Total Centers": total,
        "Bronx Centers": bronx,
        "Bronx Share": pct}

bronx_concentration = pd.DataFrame([
    bronx_share(centers_with_violations, "All centers with violations"),
    bronx_share(centers_with_violations.head(250), "Top 250 by recurrence_score"),
    bronx_share(centers_with_violations.head(100), "Top 100 by recurrence_score"),
    bronx_share(centers_with_violations.head(50), "Top 50 by recurrence_score"),
    bronx_share(centers_with_violations.head(10), "Top 10 by recurrence_score")])

# Format percent for display
bronx_concentration["Bronx Share %"] = (
    bronx_concentration["Bronx Share"] * 100).round(1)

bronx_concentration

,Group,Total Centers,Bronx Centers,Bronx Share,Bronx Share %
0,All centers with violations,1684,279,0.165677,16.6
1,Top 250 by recurrence_score,250,119,0.476000,47.6
2,Top 100 by recurrence_score,100,64,0.640000,64.0
3,Top 50 by recurrence_score,50,33,0.660000,66.0
4,Top 10 by recurrence_score,10,6,0.600000,60.0

In [ ]:
# Only centers with 1+ recurring violations
recurring_centers = center_recurrence[
    center_recurrence["recurrence_score"] > 0
].copy()

# Sort by recurrence severity
recurring_centers = recurring_centers.sort_values(
    "recurrence_score",
    ascending=False)
def bronx_share(df, label):
    total = len(df)
    bronx = (df["borough"]
        .str.upper()
        .eq("BRONX")
        .sum())
    return {"Group": label,
        "Total recurring violators in group": total,
        "Bronx recurring violators": bronx,
        "Bronx share (%)": round(bronx / total * 100, 1) if total > 0 else 0}

bronx_concentration_recurring = pd.DataFrame([
    bronx_share(recurring_centers, "All recurring violators"),
    bronx_share(recurring_centers.head(250), "Top 250 recurring violators"),
    bronx_share(recurring_centers.head(100), "Top 100 recurring violators"),
    bronx_share(recurring_centers.head(10), "Top 10 recurring violators")])

bronx_concentration_recurring

In [ ]:
# Most common top repeat violations among top 100 repeat violators
pd.set_option("display.max_colwidth", None)

top_repeaters = (
    center_recurrence
    .sort_values("recurrence_score", ascending=False)
)

# Find borough associated with highest repeat count
borough_of_max = (
    top_repeaters
    .sort_values(
        "max_times_same_violation_seen",
        ascending=False
    )
    .drop_duplicates("top_repeat_violation")
    [   [       "top_repeat_violation",
            "borough",
            "center_names",
            "max_times_same_violation_seen"
        ]
    ]
    .rename(columns={
        "borough": "borough_with_max_repeat",
        "center_names": "center_with_max_repeat"
    })
)

# Aggregate violation counts
top_repeat_violation_counts = (
    top_repeaters
    .groupby("top_repeat_violation")
    .agg(
        count=("Center_Site_ID", "count"),
        max_times_same_violation_seen=(
            "max_times_same_violation_seen",
            "max")
    )
    .reset_index())

# Merge borough info
top_repeat_violation_counts = (
    top_repeat_violation_counts
    .merge(
        borough_of_max[
            [
                "top_repeat_violation",
                "borough_with_max_repeat"            ]
        ],
        on="top_repeat_violation",
        how="left"
    )
    .sort_values("count", ascending=False)
    .head(10))

top_repeat_violation_counts

In [ ]:
pd.set_option("display.max_colwidth", None)

# Top 100 centers by recurrence score
top100_repeaters = (
    center_recurrence
    .sort_values("recurrence_score", ascending=False)
    .head(100)
    .copy()
)

# Create Bronx / non-Bronx flag
top100_repeaters["bronx_flag"] = top100_repeaters["borough"].str.upper().eq("BRONX")

# Aggregate top repeat violations
top10_repeat_violation_counts = (
    top100_repeaters
    .groupby("top_repeat_violation")
    .agg(
        centers_where_this_was_top_repeat=("Center_Site_ID", "count"),
        bronx_centers=("bronx_flag", "sum"),
        non_bronx_centers=("bronx_flag", lambda x: (~x).sum()),
        max_times_same_violation_seen=("max_times_same_violation_seen", "max")
    )
    .reset_index()
    .sort_values(
        "centers_where_this_was_top_repeat",
        ascending=False)
    .head(10))

top10_repeat_violation_counts

In [ ]:
##percent of total violations that are general

# Total recurring violations by category
recurring_violation_breakdown = (
    code_counts
    .groupby("Violation_Category_Clean")["recurrence_score"]
    .sum()
    .reset_index()
)

# Percent of all recurring violations
total_recurring = (
    recurring_violation_breakdown["recurrence_score"]
    .sum()
)

recurring_violation_breakdown["percent_of_recurring"] = (
    recurring_violation_breakdown["recurrence_score"]
    / total_recurring
    * 100
).round(1)

recurring_violation_breakdown

In [ ]:
# Bronx share vs borough baseline

# 1. Bronx share of ALL childcare centers citywide
total_citywide_centers = (
    All_Centers["Center_Site_ID"]
    .nunique())

bronx_citywide_centers = (
    All_Centers[
        All_Centers["Borough"]
        .str.upper()
        .eq("BRONX")
    ]["Center_Site_ID"]
    .nunique())

bronx_citywide_share = (
    bronx_citywide_centers
    / total_citywide_centers
    * 100)

# 2. Bronx share of recurring violators
recurring_centers = center_recurrence[
    center_recurrence["recurrence_score"] > 0
].copy()

total_recurring_centers = (
    recurring_centers["Center_Site_ID"]
    .nunique())

bronx_recurring_centers = (
    recurring_centers[
        recurring_centers["borough"]
        .str.upper()
        .eq("BRONX")
    ]["Center_Site_ID"]
    .nunique())

bronx_recurring_share = (
    bronx_recurring_centers
    / total_recurring_centers
    * 100)


# 3. Overrepresentation multiplier
overrepresentation_ratio = (
    bronx_recurring_share
    / bronx_citywide_share)

# Output table
bronx_baseline = pd.DataFrame({
    "Metric": [
        "All NYC childcare centers",
        "Recurring violators"],
    "Bronx centers": [
        bronx_citywide_centers,
        bronx_recurring_centers],
    "Total centers": [
        total_citywide_centers,
        total_recurring_centers],
    "Bronx share (%)": [
        round(bronx_citywide_share, 1),
        round(bronx_recurring_share, 1)]
})

bronx_baseline

In [ ]:
# Count total childcare centers by borough

borough_counts = (
    All_Centers
    .groupby("Borough")["Center_Site_ID"]
    .nunique()
    .reset_index(name="total_centers")
    .sort_values("total_centers", ascending=False)
)

# Add percent of citywide total
borough_counts["pct_citywide"] = (
    borough_counts["total_centers"]
    / borough_counts["total_centers"].sum()
    * 100
).round(1)

borough_counts

In [20]:
# Repeat violators = centers with recurrence_score > 0
repeat_violators = center_recurrence[
    center_recurrence["recurrence_score"] > 0
].copy()

# Count repeat violators by borough
repeat_by_borough = (
    repeat_violators
    .groupby("borough")["Center_Site_ID"]
    .nunique()
    .reset_index(name="# of repeat violators")
)

# Count total child care centers by borough
total_by_borough = (
    All_Centers
    .groupby("Borough")["Center_Site_ID"]
    .nunique()
    .reset_index(name="# of total child care centers")
    .rename(columns={"Borough": "borough"})
)

# Merge together
borough_table = total_by_borough.merge(
    repeat_by_borough,
    on="borough",
    how="left"
)

# Fill boroughs with zero repeat violators
borough_table["# of repeat violators"] = (
    borough_table["# of repeat violators"]
    .fillna(0)
    .astype(int)
)

# Calculate percent of borough with repeat violators
borough_table["% of borough with repeat violators"] = (
    borough_table["# of repeat violators"]
    / borough_table["# of total child care centers"]
    * 100
).round(0).astype(int).astype(str) + "%"

# Clean borough names
borough_table["Borough"] = borough_table["borough"].str.title()

# Reorder columns
borough_table = borough_table[
    [
        "Borough",
        "# of repeat violators",
        "# of total child care centers",
        "% of borough with repeat violators"
    ]
]

# Sort by repeat violators descending
borough_table = borough_table.sort_values(
    "# of repeat violators",
    ascending=False
)

borough_table

,Borough,# of repeat violators,# of total child care centers,% of borough with repeat violators
0,Bronx,178,293,61%
3,Queens,150,469,32%
1,Brooklyn,96,875,11%
2,Manhattan,77,488,16%
4,Staten Island,14,100,14%